import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Navbar from "@/components/Navbar";


const playfair = Playfair({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={playfair.className} >
      <body className="h-full" >
        
        <Providers >
          <div className="flex flex-col min-h-screen ">
         <Navbar ></Navbar>
         <div className="flex flex-col grow">
          {children}
         </div>
        
        </div>
        </Providers>
        
       
      
        </body>
    </html>
  );
}
